logging:
  level:
    com.kroger: DEBUG
    org.springframework: ERROR
    com.zaxxer.hikari: DEBUG
    com.zaxxer.hikari.HikariConfig: ERROR
spring:
  batch:
    jdbc:
      initialize-schema: never
      table-prefix: store_price.BATCH_
    chunk-size: ${spring-batch-chunk-size}
    job:
      enabled: false
  application:
    name: magic-data-processor
  datasource:
    url: ${azsql-magic-db-url}
    username: ${azsql-magic-db-username}
    password: ${azsql-magic-db-password}
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    hikari:
      maximum-pool-size: ${azsql-magic-db-pool-size}
      connectionTimeout: ${azsql-magic-db-connection-timeout}
      minimumIdle: ${azsql-magic-db-minimum-idle}
      idleTimeout: ${azsql-magic-db-idle-timeout}
      maxLifetime: ${azsql-magic-db-max-lifetime}
      schema: ${azsql-magic-db-schema}
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate.hibernate.default_schema: ${azsql-magic-db-schema}
    database: sql_server
  kafka:
    bootstrap-servers: ${kafka-bootstrap-servers}
    schema-registry-url: ${kafka-schema-registry-url}
    security-protocol: SASL_SSL
    schema-registry-secret: ${kafka-schema-registry-secret}
    producer:
      sasl-mechanism: OAUTHBEARER
      acks: all
      o-auth-config:
        producer-client-id: ${kafka-producer-client-id}
        producer-tenant-id: ${kafka-producer-tenant-id}
        producer-client-key: ${kafka-producer-client-key}
    mes:
      request-timeout-ms-config: ${kafka-request-timeout-ms-config}
      buffer-memory-config: ${kafka-buffer-memory-config}
      linger-ms-config: ${kafka-linger-ms-config}
      max-request-size-config: ${kafka-max-request-size-config}
      batch-size-config: ${kafka-batch-size-config}
      retries-config: ${kafka-retries-config}
      max-age: ${kafka-metadata-max-age}
      enable-idempotence: ${kafka-enable-idempotence}
app:
  target-topic: merchandising-price
  magic.file-input: /Users/dou2267/development/magic-data-processor/src/main/resources/data/magic-data.txt

